##### Numpy Array 

Numpy Array VS Python list  


In [1]:
import numpy as np

In [4]:
import time
start = time.time()
py_list  = [i*2 for i in range(1000000)]
print("\n List Operation time : ", time.time() - start)


 List Operation time :  0.08238077163696289


In [3]:
start = time.time()
np_arry = np.arange(1000000) * 2
print("\n Numpy operation time : ", time.time() - start)


 Numpy operation time :  0.021179676055908203


##### Creating Numpy Array 

In [ ]:
# Create Numpy Array using the zeros

zeros = np.zeros((3,4)) 
print("Zeros array : \n",zeros)

# Crating numpy one's array 
ones = np.ones((4,4))
print("Numpy Ones Array : \n", ones)

# Creating a numpy array with a constant value

const_val = np.full((3,3),5) # creating a contant array with the value 5
print("Numpy Constant Value Array :\n",const_val)



Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Numpy Ones Array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Numpy Constant Value Array :
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


##### Randomness 

In [12]:
# Creating a array with the random number 

random = np.random.random((3,3)) 
print("Random list 3X3:\n",random)

# Creating a sequence array 

seq_arr = np.arange(0,11,2)
print("Sequence Array:\n",seq_arr)

Random list 3X3:
 [[0.52767523 0.85905693 0.05599309]
 [0.75022222 0.14890139 0.45911459]
 [0.10956317 0.79824128 0.41557302]]
Sequence Array:
 [ 0  2  4  6  8 10]
